---

- hosts: all
  become: true
  tasks:

  - name: install packages on Pop
    apt:
      name: 
        - apache2
        - nala
        - btop
      state: latest
    when: ansible_distribution == "Pop!_OS" #when: ansible_distrubution in ["Pop!_OS", "Ubuntu"]
 
  - name: install packages on Ubuntu
    apt:
      name:         
        - apache2
        - nala
        - btop
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: install packages on Rocky
    dnf:
      name: 
        - httpd
        - btop
      state: latest
    when: ansible_distribution == "Rocky"

#RHEL does not enable services by default
  - name: enable apache2, aka httpd
    systemd:
      name: httpd
      enabled: yes
      state: started
    when: ansible_distribution == "Rocky"