---
- name: Install a package on multiple OSs
  hosts: all
  become: yes

  vars:
    package_name: "btop"

  tasks:
    - name: Determine OS family
      set_fact:
        os_family: "{{ ansible_facts['os_family'] }}"

    - name: Install package on Debian-based systems (Pop!_OS, Ubuntu)
      apt:
        name: "{{ package_name }}"
        state: present
      when: os_family == "Debian"

    - name: Install package on Rocky Linux
      yum:
        name: "{{ package_name }}"
        state: present
      when: os_family == "RedHat"

